### ISSUE TITLE
can't build Bio-BigFile

### ISSUE THREAD

**Issue by hkmztrk** [GMOD/GBrowse-Adaptors#22]
Hello, not sure if anyone is active here but directed here by https://github.com/ucscGenomeBrowser/kent/issues/51

Here is my problem,

I am trying to install Bio-BigFile-1.07 and consistently getting this error after` ./Build`

```
Building Bio-BigFile
cc -shared -O2 -L/usr/local/lib -fstack-protector -o blib/arch/auto/Bio/DB/BigFile/BigFile.so lib/Bio/DB/BigFile.o ~/kent/src/lib/x86_64/jkweb.a -lz -lssl
/usr/bin/ld: ~/kent/src/lib/x86_64/jkweb.a(bbiRead.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
~/kent/src/lib/x86_64/jkweb.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
error building blib/arch/auto/Bio/DB/BigFile/BigFile.so from lib/Bio/DB/BigFile.o at /software/perl/5.24.1/lib/5.20.2/ExtUtils/CBuilder/Base.pm line 323.
```

I updated the `CFLAGS=-fPIC` in kent/src/inc/common.mk and run make in kent/src/lib
Also followed the below instructions:

```
export MACHTYPE=x86_64
export PATH="~/bin/$MACHTYPE:$PATH
```

I also tried what is suggested here: http://seqanswers.com/forums/archive/index.php/t-70219.html

run `make` in Kent folders with following:
`make CXXFLAGS=-fPIC CFLAGS=-fPIC CPPFLAGS=-fPIC`

After this I'm finally passing` ./Build` but this time  ` ./Build test` fails, 

```
Test Summary Report
-------------------
t/01.bigwig.t     (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 29 tests but ran 0.
t/02.bigbed.t     (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 15 tests but ran 0.
t/03.bigwig_high.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 32 tests but ran 0.
t/04.bigbed_high.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 35 tests but ran 0.
t/05.bigwig_set.t (Wstat: 512 Tests: 0 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=5, Tests=0,  2 wallclock secs ( 0.07 usr  0.03 sys +  1.39 cusr  0.41 csys =  1.90 CPU)
Result: FAIL
Failed 5/5 test programs. 0/0 subtests failed.
```

 It'd be great if you can help me about this.

**Comment by tjparnell** [comment]
Hi @hkmztrk,

I am not one of the developers, but I have been a very long time user. 

This project, and GBrowse in general, is barely supported anymore, so you will have to keep that in mind. The best thing to do is to step back in time, essentially, by using older versions. If you recently obtained the UCSC code, you may want to download an older version, as it's entirely possible that they have subtly changed their libraries that prevent the XS libraries here from working as expected. Any incompatibilities are unlikely to be detected, let alone fixed. For example, you can browse older releases of the userApps at [UCSC archive](http://hgdownload.soe.ucsc.edu/admin/exe/userApps.archive/). I've successfully compiled numerous times using the userApps, which is considerably smaller, rather than the full blown UCSC web browser code. 

I have some instructions on compiling this specific module in a [help document](https://github.com/tjparnell/biotoolbox/blob/master/docs/AdvancedInstallation.md#ucsc-bigfile-library) in my own project. I mentioned release 375 (circa 2018) in the document, and I am sure earlier releases have worked. A second point is to make sure you grab the tarball from here, not CPAN, as the CPAN release is not up to date.

Finally, if you're just interested in simply bigWig access using Perl code, you can try looking at [Bio-DB-Big](https://github.com/Ensembl/Bio-DB-Big). It won't work with GBrowse, but it's at least a little easier to install than this one.

Good luck!

**Comment by hkmztrk** [comment]
Hello @tjparnell, your solution works like a charm!! Huge thanks!! I am no longer stuck at `./Build test`. 

My only obstacle is now `./Build install` - I'm getting permission error since I try to install this on cluster. I used `perl Build.PL PREFIX=~/lib/perl5` but it doesn't seem to be working. Anyway I'm sure there should be some solution for this! 

I am trying to get PhyloP scores through VEP and it needed Bio-BigFile, that's why I didn't look at other alternatives. But thanks a lot for the suggestion.
